server:
  port: 8080

logging:
  config: classpath:logback-spring.xml

spring:
  datasource:
    name: datasource
    url: jdbc:mysql://192.168.3.54:3306/entrusts?useUnicode=true&characterEncoding=utf-8
    username: root
    password: rootroot
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    maxActive: 50
    initialSize: 10
    maxWait: 10000
    minIdle: 10
    timeBetweenEvictionRunsMillis: 300000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
  application:
    name: entrusts

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

redis:
  database: 20
  host: 192.168.3.31
  password: dev@Mo9.com

  database2: 21
  host2: 192.168.3.31
  password2: dev@Mo9.com

  port: 6379
  timeout: 20000
  maxTotal: 50
  maxWait: 10000
  maxIdle: 10
  minIdle: 0

mq:
  productId: PID_MO9_CLONE_ENTRUSTS
  accessKey: LTAIyDR4k37NBuJu
  secretKey: XRDykcat39ONcoCi1OZ7cpfohm1Yyk
  delegatePushTopic: TOPIC_MO9_CLONE_ENTRUSTS_DELEGATE_PUSH
  delegatePushTag: TAG_MO9_CLONE_ENTRUSTS_DELEGATE_PUSH
  sendMsgTimeoutMillis: 3000
  onsAddr: http://onsaddr-internet.aliyun.com/rocketmq/nsaddr4client-internet

datacenterId: 1
machineId: 1

## 用户中心配置
#nest.url=http://192.168.1.33:8180/nestApi/
#nest.url=http://d-eoc-0038.mo9.com:8180/
## 用户中心配置
#nest.url=http://nest.alpha.mo9.com/nestApi/
#nest.url=http://d-eoc-0038.mo9.com:8180/
#nest.mode=ALONE
#nest.exclude.urls=/api/dandelion/v1/auth/**,/error
#nest.exclude.urls=${container.name}/api/dandelion/v1/auth/**,/error
#nest.exclude.urls=${container.name}/api/dandelion/v1/auth/**,${container.name}/bk/api/dandelion/v1/**,/error
#nest.secret=9a1c4351260c460596357f0b4f1a894d
#nest.key=5c94b03fedbe43e1a1f2822a91a5143f
#nest.code=Dandelion
#nest.group=DandelionGroup

nest:
  url: http://nest.alpha.mo9.com/nestApi/
  key: 5c94b03fedbe43e1a1f2822a91a5143f
  secret: 9a1c4351260c460596357f0b4f1a894d
  code: Dandelion
  group: DandelionGroup
  mode: ALONE
  exclude:
    urls: /auth/**,/error,/captcha/**,/order/requestToken,/order/delegateLimit,/entrusts/currency/listBase,/entrusts/currency/listTarget,/entrusts/currency/allListTarget,/entrusts/order/cancel,/entrusts/order/cancelAll


mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-handlers-package: com.entrusts.util

disruptor:
  delegateEvent:
    bufferSize: 1024
    publishOrderThreadNum: 50

httpclient:
  pool:
    maxTotal: 500
    defaultMaxPerRoute: 200

feign:
  httpclient:
    enabled: true

ribbon:
  ConnectTimeout: 500
  ReadTimeout: 10000
  OkToRetryOnAllOperations: false
  MaxAutoRetriesNextServer: 0
  MaxAutoRetries: 0

feignName:
  #钱包系统
  millstoneName: client-service
  #撮单系统
  dealmakingName: springcloud-client

url:
  lockCoin: www
  urldealmaking: http://192.168.6.27:3000/mock/104
